{
  "timestamp": "2025-10-28T20:43:12.526094",
  "status": {
    "error": "HTTPConnectionPool(host='localhost', port=5081): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000250B83FF770>: Failed to establish a new connection: [WinError 10061] Aucune connexion n\u2019a pu \u00eatre \u00e9tablie car l\u2019ordinateur cible l\u2019a express\u00e9ment refus\u00e9e'))"
  },
  "hashes": {
    "Invoke-AgentSecure.py": "eb83863322997968cc29641f49da9397ef3c10d24ae5f0d566e2168cc2ec4892",
    "autopilot_server.py": "9bbca452bf7b0ce0d3ebba6069ae68833389062240228ec33019a787c09757ff"
  }
}